version: '3'
services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql_project_withdocker_container
    environment:
      MYSQL_ROOT_PASSWORD: 1453
      MYSQL_DATABASE: tkk_proje
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
